// Autogenerated using mud system-types
import { ComponentDevSystem } from "./ethers-contracts/ComponentDevSystem";
import { SpawnEntitySystem } from "./ethers-contracts/SpawnEntitySystem";
 
export type SystemTypes = {
  "mudwar.system.ComponentDev": ComponentDevSystem;
  "system.SpawnEntity": SpawnEntitySystem;
};
