// Autogenerated using mud system-types
export const systemToId = {
  ComponentDevSystem: "mudwar.system.ComponentDev",
  MoveByTwoSystem: "system.MoveByTwo",
  MoveSystem: "system.Move",
  SpawnEntitySystem: "system.SpawnEntity",
};

export const idToSystem = {
  "mudwar.system.ComponentDev": "ComponentDevSystem",
  "system.MoveByTwo": "MoveByTwoSystem",
  "system.Move": "MoveSystem",
  "system.SpawnEntity": "SpawnEntitySystem",
};
  