// Autogenerated using mud system-types
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import SpawnEntitySystem from "../abi/SpawnEntitySystem.json";

export const SystemAbis = {
  "mudwar.system.ComponentDev": ComponentDevSystem.abi,
  "system.SpawnEntity": SpawnEntitySystem.abi,
};
