// Autogenerated using mud system-types
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import MoveByTwoSystem from "../abi/MoveByTwoSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import SpawnEntitySystem from "../abi/SpawnEntitySystem.json";

export const SystemAbis = {
  "mudwar.system.ComponentDev": ComponentDevSystem.abi,
  "system.MoveByTwo": MoveByTwoSystem.abi,
  "system.Move": MoveSystem.abi,
  "system.SpawnEntity": SpawnEntitySystem.abi,
};
