// Autogenerated using mud system-types
import { ComponentDevSystem } from "./ethers-contracts/ComponentDevSystem";
import { MoveByTwoSystem } from "./ethers-contracts/MoveByTwoSystem";
import { MoveSystem } from "./ethers-contracts/MoveSystem";
import { SpawnEntitySystem } from "./ethers-contracts/SpawnEntitySystem";
 
export type SystemTypes = {
  "mudwar.system.ComponentDev": ComponentDevSystem;
  "system.MoveByTwo": MoveByTwoSystem;
  "system.Move": MoveSystem;
  "system.SpawnEntity": SpawnEntitySystem;
};
