// Autogenerated using mud system-types
export const systemToId = {
  ComponentDevSystem: "mudwar.system.ComponentDev",
  SpawnEntitySystem: "system.SpawnEntity",
};

export const idToSystem = {
  "mudwar.system.ComponentDev": "ComponentDevSystem",
  "system.SpawnEntity": "SpawnEntitySystem",
};
  